chore: add arm64 linux build

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -23,3 +23,16 @@ jobs:
         run: go mod download
       - name: Run tests
         run: go test ./...
+      - name: Prepare/Release Workflows Check
+        run: |
+          go install github.com/mikefarah/yq/v4@latest
+          yq '.jobs.release.steps.[0:11]' .github/workflows/release.yaml > release-steps.yaml
+          yq '.jobs.prepare.steps' .github/workflows/prepare.yaml > prepare-steps.yaml
+          if ! diff release-steps.yaml prepare-steps.yaml; then
+            echo "Prepare and Release workflows are not in sync!"
+            exit 1
+          fi
+          if ! yq '.jobs.release.steps.[11]' .github/workflows/release.yaml | grep -q 'Create Release'; then
+            echo 'Release has pre-build steps missing from Prepare workflow!'
+            exit 1
+          fi
